SET(CMAKE_SYSTEM_NAME Kiznix)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(CMAKE_SYSTEM_VERSION 1)

INCLUDE(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(x86_64-elf-gcc GNU)
CMAKE_FORCE_CXX_COMPILER(x86_64-elf-gcc GNU)

SET(CMAKE_C_SIZEOF_DATA_PTR 8)

SET(COMMON_FLAGS "-O2 -ffreestanding -fbuiltin -Wall -Wextra -mcmodel=kernel -mno-red-zone")
SET(CMAKE_C_FLAGS "${COMMON_FLAGS} -std=gnu99" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "${COMMON_FLAGS} -fno-exceptions -fno-rtti" CACHE STRING "" FORCE)
